version: 2
jobs:
  build:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - restore_cache:
          key: dependencies-{{ checksum "package.json" }}

      - run: npm install
      - run: npm test

      - save_cache:
          key: dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules
